"""Renombrar empr

Revision ID: 291fe01988cd
Revises: 
Create Date: 2025-09-30 00:39:48.777160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291fe01988cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aviso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=500), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('icono', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('lugar', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noticia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('negocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('redes', sa.String(length=255), nullable=True),
    sa.Column('horario', sa.String(length=120), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('perfil_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('sitio_web', sa.String(length=255), nullable=True),
    sa.Column('facebook', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('tiktok', sa.String(length=255), nullable=True),
    sa.Column('horario', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('perfil_empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_perfil_empresa_usuario_id'), ['usuario_id'], unique=True)

    op.create_table('aviso_ciudadano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aviso_ciudadano', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aviso_ciudadano_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_aviso_ciudadano_perfil_id'), ['perfil_id'], unique=False)

    op.create_table('evento_ciudadano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('lugar', sa.String(length=255), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evento_ciudadano', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evento_ciudadano_fecha_fin'), ['fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_evento_ciudadano_fecha_inicio'), ['fecha_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_evento_ciudadano_perfil_id'), ['perfil_id'], unique=False)

    op.create_table('noticia_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('noticia_empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_noticia_empresa_fecha_publicacion'), ['fecha_publicacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_noticia_empresa_perfil_id'), ['perfil_id'], unique=False)

    op.create_table('oferta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oferta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oferta_fecha_fin'), ['fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_oferta_fecha_inicio'), ['fecha_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_oferta_perfil_id'), ['perfil_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oferta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oferta_perfil_id'))
        batch_op.drop_index(batch_op.f('ix_oferta_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_oferta_fecha_fin'))

    op.drop_table('oferta')
    with op.batch_alter_table('noticia_empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_noticia_empresa_perfil_id'))
        batch_op.drop_index(batch_op.f('ix_noticia_empresa_fecha_publicacion'))

    op.drop_table('noticia_empresa')
    with op.batch_alter_table('evento_ciudadano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_ciudadano_perfil_id'))
        batch_op.drop_index(batch_op.f('ix_evento_ciudadano_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_evento_ciudadano_fecha_fin'))

    op.drop_table('evento_ciudadano')
    with op.batch_alter_table('aviso_ciudadano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aviso_ciudadano_perfil_id'))
        batch_op.drop_index(batch_op.f('ix_aviso_ciudadano_creado_en'))

    op.drop_table('aviso_ciudadano')
    with op.batch_alter_table('perfil_empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_perfil_empresa_usuario_id'))

    op.drop_table('perfil_empresa')
    op.drop_table('negocio')
    op.drop_table('usuario')
    op.drop_table('noticia')
    op.drop_table('evento')
    op.drop_table('categoria')
    op.drop_table('aviso')
    # ### end Alembic commands ###
