"""Add fecha_registro to Usuario3333

Revision ID: 37f8adc120b2
Revises: 842b9799c928
Create Date: 2025-10-11 20:13:52.545311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f8adc120b2'
down_revision = '842b9799c928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oferta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oferta_fecha_fin'))
        batch_op.drop_index(batch_op.f('ix_oferta_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_oferta_perfil_id'))

    op.drop_table('oferta')
    with op.batch_alter_table('aviso_ciudadano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aviso_ciudadano_perfil_id'))

    with op.batch_alter_table('evento_ciudadano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_ciudadano_perfil_id'))
        batch_op.create_index(batch_op.f('ix_evento_ciudadano_creado_en'), ['creado_en'], unique=False)

    with op.batch_alter_table('noticia_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_noticia_empresa_fecha_publicacion'))
        batch_op.drop_index(batch_op.f('ix_noticia_empresa_perfil_id'))
        batch_op.create_index(batch_op.f('ix_noticia_empresa_creado_en'), ['creado_en'], unique=False)
        batch_op.drop_column('fecha_publicacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_publicacion', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_noticia_empresa_creado_en'))
        batch_op.create_index(batch_op.f('ix_noticia_empresa_perfil_id'), ['perfil_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_noticia_empresa_fecha_publicacion'), ['fecha_publicacion'], unique=False)
        batch_op.drop_column('creado_en')

    with op.batch_alter_table('evento_ciudadano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_ciudadano_creado_en'))
        batch_op.create_index(batch_op.f('ix_evento_ciudadano_perfil_id'), ['perfil_id'], unique=False)

    with op.batch_alter_table('aviso_ciudadano', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aviso_ciudadano_perfil_id'), ['perfil_id'], unique=False)

    op.create_table('oferta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=150), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=False),
    sa.Column('imagen', sa.VARCHAR(length=255), nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), nullable=True),
    sa.Column('fecha_fin', sa.DATE(), nullable=True),
    sa.Column('creado_en', sa.DATETIME(), nullable=True),
    sa.Column('perfil_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oferta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oferta_perfil_id'), ['perfil_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oferta_fecha_inicio'), ['fecha_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_oferta_fecha_fin'), ['fecha_fin'], unique=False)

    # ### end Alembic commands ###
