"""Renamed ciudadano models

Revision ID: 73af8860326a
Revises: 37f8adc120b2
Create Date: 2025-10-11 20:22:46.109462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73af8860326a'
down_revision = '37f8adc120b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aviso_ciudadano', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aviso_ciudadano_perfil_id'), ['perfil_id'], unique=False)

    with op.batch_alter_table('evento_ciudadano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_ciudadano_creado_en'))
        batch_op.create_index(batch_op.f('ix_evento_ciudadano_perfil_id'), ['perfil_id'], unique=False)

    with op.batch_alter_table('noticia_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_publicacion', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_noticia_empresa_creado_en'))
        batch_op.create_index(batch_op.f('ix_noticia_empresa_fecha_publicacion'), ['fecha_publicacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_noticia_empresa_perfil_id'), ['perfil_id'], unique=False)
        batch_op.drop_column('creado_en')

    with op.batch_alter_table('oferta_ciudadano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oferta_ciudadano_creado_en'))
        batch_op.create_index(batch_op.f('ix_oferta_ciudadano_perfil_id'), ['perfil_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oferta_ciudadano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oferta_ciudadano_perfil_id'))
        batch_op.create_index(batch_op.f('ix_oferta_ciudadano_creado_en'), ['creado_en'], unique=False)

    with op.batch_alter_table('noticia_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_noticia_empresa_perfil_id'))
        batch_op.drop_index(batch_op.f('ix_noticia_empresa_fecha_publicacion'))
        batch_op.create_index(batch_op.f('ix_noticia_empresa_creado_en'), ['creado_en'], unique=False)
        batch_op.drop_column('fecha_publicacion')

    with op.batch_alter_table('evento_ciudadano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_ciudadano_perfil_id'))
        batch_op.create_index(batch_op.f('ix_evento_ciudadano_creado_en'), ['creado_en'], unique=False)

    with op.batch_alter_table('aviso_ciudadano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aviso_ciudadano_perfil_id'))

    # ### end Alembic commands ###
