"""Agregar campo imagen a Noticia, Aviso y Evento3

Revision ID: 842b9799c928
Revises: 
Create Date: 2025-10-11 18:33:46.573288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842b9799c928'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###
