"""estructuraw 

Revision ID: 618e22abc514
Revises: 7da8bf840672
Create Date: 2025-09-29 22:20:19.933160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618e22abc514'
down_revision = '7da8bf840672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('sitio_web', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tiktok', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('horario', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_perfil_empresa_usuario_id'))
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['id'])
        batch_op.drop_column('redes')
        batch_op.drop_column('actualizado_en')
        batch_op.drop_column('creado_en')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfil_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creado_en', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('actualizado_en', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('redes', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_perfil_empresa_usuario_id'), ['usuario_id'], unique=False)
        batch_op.drop_column('categoria_id')
        batch_op.drop_column('horario')
        batch_op.drop_column('tiktok')
        batch_op.drop_column('instagram')
        batch_op.drop_column('facebook')
        batch_op.drop_column('sitio_web')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
